import {
    LayoutDashboard,
    FileText,
    FileMinus,
    BookLock,
    BookKey,
    ShelvingUnit,
    ArrowRightLeft,
    ClipboardList,
    ShoppingCart,
    HandCoins,
    Tag,
    ContactRound,
    IdCardLanyard,
    BookOpen,
    ChartLine,
    User,
    Store,
    Shield,
    LogOut,
    ChevronRight,
    ChevronDown,
    Menu,
    X,
    ChevronsDown,
    ChevronsUp,
    EllipsisVertical,
    Plus
} from 'lucide-react'

export const Icons = {
  dashboard:        LayoutDashboard,
  factura:          FileText,
  credito:          FileMinus,
  cierreCaja:       BookLock,
  aperturaCaja:     BookKey,
  inventario:       ShelvingUnit,
  traslado:         ArrowRightLeft,
  cierreInventario: ClipboardList,
  compras:          ShoppingCart,
  cxp:              HandCoins,
  productos:        Tag,
  clientes:         ContactRound,
  vendedores:       IdCardLanyard,
  catalogo:         BookOpen,
  reporte:          ChartLine,
  usuario:          User,
  tienda:           Store,
  audit:            Shield,
  logout:           LogOut,
  flechaDerecha:    ChevronRight,
  flechaAbajo:      ChevronDown,
  menu:             Menu,
  equis:            X,
  collapse:         ChevronsUp,
  expand:           ChevronsDown,
  ellipsis:         EllipsisVertical,
  plus:             Plus
}